my:
  name: 张三
  gender: 女
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud: 
    bus:
      enabled: true
      trace: 
        enabled: true
        
management:
  endpoints: 
    web: 
      exposure: 
        include: "*"